### ISSUE TITLE
what's the meaning of the 6th column in genebody_anno_hg19.txt?

### ISSUE THREAD

**Issue by RyanZhiNie** [KunFang93/NucHMM#3]
Hi, Kun Fang. Your work is interesting and impressive, and I wanna apply NucHMM to my own data. I have preprocessed my nucleosome data and histone modification data, however, the reference genome I used was hg38, while it seems that the default reference genome in NucHMM is hg19. So, I tried to make genebody_anno_hg38.txt, instead of using genebody_anno_hg19.txt in NucHMM. But what's the meaning of the 6th column in genebody_anno_hg19.txt? I found the `segment_gene` function uses this file but it seems that the 6th column is not used. Thanks in advance.

**Comment by KunFang93** [comment]
Hi, Zhi

Thanks for interesting in NucHMM. You're right. The 6th is the gene ID which is not used in the program. You could use 5 columns reference genome.

Best,
Kun

**Comment by RyanZhiNie** [comment]
Got it!
Thanks for your timely reply and I have successfully made the file.
